name: News Bot

# on:
#   schedule:
#     - cron: "50 5,19 * * *" # Run daily at 4:50AM and 2:50PM KST (UTC+9)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Seoul"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Set Timezone to Asia/Seoul
        run: sudo timedatectl set-timezone Asia/Seoul
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run main.py
        run: python main.py
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
